#!/usr/bin/env bash
# 03-rds.sh — RDS PostgreSQL 16, db.t4g.medium, 50GB gp3, single-AZ, 7-day
# backups, NOT publicly accessible, reachable only from hr-staging-ec2-sg.
# `CREATE EXTENSION vector` is applied later (07-ec2.sh / this session's end)
# from inside the VPC, once the EC2 exists — RDS is never opened publicly to
# do it.
#
# Idempotent: describes first; only creates if absent. Master password is
# read fresh from SSM (generated by 05-ssm-params.sh) and passed directly
# into the create-db-instance call — never echoed, never written to a file.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
source ./vars.sh

if aws rds describe-db-instances --db-instance-identifier "$NAME_RDS_INSTANCE" >/dev/null 2>&1; then
  STATUS=$(aws rds describe-db-instances --db-instance-identifier "$NAME_RDS_INSTANCE" \
    --query 'DBInstances[0].DBInstanceStatus' --output text)
  log "${NAME_RDS_INSTANCE} already exists (status: ${STATUS}) — skipping create."
else
  RDS_SG_ID=$(cat "${LOCAL_STATE_DIR}/rds_sg_id")
  DB_SUBNET_GROUP="$NAME_DB_SUBNET_GROUP"
  MASTER_PASSWORD=$(aws ssm get-parameter --name "$SSM_RDS_MASTER_PASSWORD" --with-decryption --query 'Parameter.Value' --output text)

  log "Creating ${NAME_RDS_INSTANCE} (this takes ~10-15 min to become available)..."
  aws rds create-db-instance \
    --db-instance-identifier "$NAME_RDS_INSTANCE" \
    --engine postgres \
    --engine-version 16 \
    --db-instance-class "$RDS_INSTANCE_CLASS" \
    --allocated-storage "$RDS_ALLOCATED_STORAGE_GB" \
    --storage-type gp3 \
    --db-name "$NAME_RDS_DB_NAME" \
    --master-username "$NAME_RDS_MASTER_USER" \
    --master-user-password "$MASTER_PASSWORD" \
    --vpc-security-group-ids "$RDS_SG_ID" \
    --db-subnet-group-name "$DB_SUBNET_GROUP" \
    --backup-retention-period "$RDS_BACKUP_RETENTION_DAYS" \
    --no-publicly-accessible \
    --no-multi-az \
    --storage-encrypted \
    --tags Key=Project,Value=hr-platform Key=Env,Value=staging Key=ManagedBy,Value=hr-docs/infra Key=Name,Value="$NAME_RDS_INSTANCE" \
    >/dev/null
  unset MASTER_PASSWORD
  log "Create request accepted. Poll with: aws rds describe-db-instances --db-instance-identifier ${NAME_RDS_INSTANCE} --query 'DBInstances[0].DBInstanceStatus'"
fi

log "03-rds.sh done (extension creation deferred to after the EC2 exists)."
