#!/usr/bin/env bash
# 08-derived-secrets.sh — compose the ONE secret that can't be a flat
# machine-generated value (05-ssm-params.sh) because it's a composition of
# other values that only exist once RDS is up: hr-ai's DATABASE_URL.
#
# hr-ai's app/config.py takes a single DSN string
# (postgresql://user:pass@host:port/db), not decomposed DB_HOST/DB_USER/...
# vars — so the entrypoint can't assemble it from separate SSM parameters at
# container-start without an app-code change. Instead this script composes
# it ONCE, now that the RDS endpoint is known, from values that already
# exist (the scoped `hr_ai` role's password, generated by 05-ssm-params.sh)
# and stores the composed DSN as its own SecureString. The password is read
# with --with-decryption directly into a shell variable and never echoed,
# written to a file, or passed as a literal CLI argument that could land in
# shell history.
#
# Idempotent: skips if the target parameter already holds a real value.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
source ./vars.sh

param_has_real_value() {
  local name="$1"
  local val
  val=$(aws ssm get-parameter --name "$name" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null) || return 1
  [[ "$val" != "SET-ME-VIA-CONSOLE" && -n "$val" ]]
}

if param_has_real_value "$SSM_HR_AI_DATABASE_URL"; then
  log "${SSM_HR_AI_DATABASE_URL}: already has a real value — leaving untouched."
  exit 0
fi

log "Resolving the RDS endpoint..."
RDS_ENDPOINT="$(aws rds describe-db-instances \
  --db-instance-identifier "$NAME_RDS_INSTANCE" \
  --query 'DBInstances[0].Endpoint.Address' --output text)"
log "  endpoint: ${RDS_ENDPOINT}"

log "Reading the hr_ai role password from SSM (not displayed)..."
HR_AI_DB_PASSWORD="$(aws ssm get-parameter \
  --name "$SSM_SHARED_HR_AI_DB_PASSWORD" --with-decryption \
  --query 'Parameter.Value' --output text)"

DSN="postgresql://hr_ai:${HR_AI_DB_PASSWORD}@${RDS_ENDPOINT}:5432/${NAME_RDS_DB_NAME}"
unset HR_AI_DB_PASSWORD

log "Storing the composed DSN at ${SSM_HR_AI_DATABASE_URL} (value never displayed)..."
if aws ssm put-parameter --name "$SSM_HR_AI_DATABASE_URL" --type SecureString \
    --value "$DSN" \
    --tags Key=Project,Value=hr-platform Key=Env,Value=staging Key=ManagedBy,Value=hr-docs/infra \
    >/dev/null 2>&1; then
  :
else
  aws ssm put-parameter --name "$SSM_HR_AI_DATABASE_URL" --type SecureString --overwrite --value "$DSN" >/dev/null
fi
unset DSN

log "08-derived-secrets.sh done."
